theme: jekyll-theme-minimal
logo: https://www.rust-lang.org/static/images/rust-logo-blk.svg
show_downloads: true
author: <a href="mailto:mail@abdus.xyz">Abdus &lt;mail@abdus.xyz&gt;</a>

collections:
  notes:
    output: true
    sort_by: date
    permalink: /:collection/:title

defaults:
  - scope:
      path: ''
      type: notes
    values:
      layout: post
